# Generated by Django 5.1.3 on 2024-12-03 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_version', models.CharField(default='0.0.0', max_length=50)),
                ('last_website_version', models.CharField(default='0.0.0', max_length=50)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('staging_mode', models.BooleanField(default=False)),
                ('staged_version', models.CharField(default='0.0.0', max_length=50)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Configuration',
                'verbose_name_plural': 'System Configuration',
            },
        ),
    ]
