# Generated by Django 5.1.3 on 2024-12-04 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemconfiguration',
            name='staged_version',
        ),
        migrations.RemoveField(
            model_name='systemconfiguration',
            name='staging_mode',
        ),
    ]
