# Generated by Django 5.1.3 on 2024-11-25 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfiguration',
            name='staged_version',
            field=models.CharField(default='0.0.0', max_length=50),
        ),
    ]
