# Generated by Django 5.1.3 on 2024-12-24 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=200, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('external_url', models.URLField(blank=True, max_length=500, null=True)),
                ('external_url_date', models.DateTimeField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='sliders/images/')),
                ('type', models.CharField(choices=[('card', 'Card'), ('image', 'Image')], max_length=5)),
            ],
            options={
                'verbose_name': 'Slider Item',
                'verbose_name_plural': 'Slider Items',
            },
        ),
    ]
