# Generated by Django 5.1.3 on 2024-12-24 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_slider_slideritem_active_slideritem_slider'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slider',
            old_name='name',
            new_name='slider_id',
        ),
    ]
