# Generated by Django 5.1.3 on 2025-01-02 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_rename_page_id_page_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slideritem',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='slideritem',
            name='external_url_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
