# Generated by Django 5.1.3 on 2025-01-03 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_alter_slideritem_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='slideritem',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
